// Shared artifact data source
export interface Artifact {
  id: string;
  title: string;
  date: string;
  location: string;
  currentLocation: string;
  description: string;
  imageUrl: string;
  modelUrl: string;
  weight: string;
  height: string;
}

export const allArtifacts: Artifact[] = [
  {
    id: "traditional-pottery",
    title: "Hulu Hulu",
    date: "14th Century",
    location: "Benin",
    currentLocation: "London, British Museum",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    imageUrl: "/images/caseStudies/artifacts/cs_a1.jpg",
    modelUrl: "/models/a101.glb",
    weight: "135.75 oz",
    height: "17.53 cm",
  },
  {
    id: "skull-233",
    title: "Rocket Launcher",
    date: "15th Century",
    location: "Bawku",
    currentLocation: "Ghana Monuments and Management Board, Accra Museum",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    imageUrl: "/images/caseStudies/artifacts/cs_a2.jpg",
    modelUrl: "/models/skele.glb",
    weight: "92.45 oz",
    height: "22.10 cm",
  },
  {
    id: "bronze-sculpture",
    title: "Nsibidi 12",
    date: "16th Century",
    location: "Benin City",
    currentLocation: "Lagos, Institute",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    imageUrl: "/images/caseStudies/artifacts/cs_a3.jpg",
    modelUrl: "/models/artifact3.glb",
    weight: "210.30 oz",
    height: "35.75 cm",
  },
  {
    id: "wooden-stone",
    title: "Obour Wooden Stone",
    date: "1850s",
    location: "East Africa",
    currentLocation: "Nairobi, Cultural Center",
    description:
      "Intricately carved wooden stool symbolizing status and craftsmanship in traditional societies. This exceptional piece represents the sophisticated woodworking traditions of East African communities.",
    imageUrl: "/images/caseStudies/artifacts/artifact4.jpg",
    modelUrl: "/models/aa12.glb",
    weight: "85.20 oz",
    height: "15.30 cm",
  },
  {
    id: "traditional-mask",
    title: "Beaded Mask",
    date: "1900s",
    location: "Southern Africa",
    currentLocation: "Cape Town, Museum",
    description:
      "Beautiful collection of beads showcasing traditional jewelry-making techniques. These beads were used not only for adornment but also as a form of communication and currency.",
    imageUrl: "/images/caseStudies/artifacts/artifact5.jpg",
    modelUrl: "/models/artifact123.gltf",
    weight: "42.75 oz",
    height: "8.25 cm",
  },
  {
    id: "textile-art-1",
    title: "Me Ne Wo Sre Kwa",
    date: "1750s",
    location: "West Africa",
    description:
      "Colorful textile artwork representing cultural stories and traditional weaving methods. Each pattern in Kente cloth has a specific meaning and significance in West African culture.",
    imageUrl: "/images/caseStudies/artifacts/artifact6.jpg",
    modelUrl: "/models/skele.glb",
    weight: "68.40 oz",
    height: "25.10 cm",
    currentLocation: "Kumasi, Cultural Institute",
  },
  {
    id: "textile-art-2",
    title: "Nyatepe",
    date: "1750s",
    location: "West Africa",
    description:
      "Colorful textile artwork representing cultural stories and traditional weaving methods. Each pattern in Kente cloth has a specific meaning and significance in West African culture.",
    imageUrl: "/images/caseStudies/artifacts/artifact7.jpg",
    modelUrl: "/models/artifact6.glb",
    weight: "68.40 oz",
    height: "25.10 cm",
    currentLocation: "Kumasi, Cultural Institute",
  },
  {
    id: "textile-art-3",
    title: "Kente Pot",
    date: "1750s",
    location: "West Africa",
    description:
      "Colorful textile artwork representing cultural stories and traditional weaving methods. Each pattern in Kente cloth has a specific meaning and significance in West African culture.",
    imageUrl: "/images/caseStudies/artifacts/artifact8.jpg",
    modelUrl: "/models/artifact6.glb",
    weight: "68.40 oz",
    height: "25.10 cm",
    currentLocation: "Kumasi, Cultural Institute",
  },
  {
    id: "african-pottery",
    title: "Traditional African Pottery",
    date: "18th Century",
    location: "West Africa",
    currentLocation: "Abidjan, Côte d'Ivoire",
    description:
      "Handcrafted pottery showcasing traditional African ceramic techniques. These vessels were used for both practical and ceremonial purposes in various West African cultures.",
    imageUrl: "/images/caseStudies/artifacts/artifact9.jpg",
    modelUrl: "/models/artifact7.glb",
    weight: "115.30 oz",
    height: "22.75 cm",
  },
  {
    id: "tribal-sculpture",
    title: "Tribal Sculpture",
    date: "19th Century",
    location: "Central Africa",
    currentLocation: "Paris, Quai Branly Museum",
    description:
      "Intricately carved wooden sculpture representing ancestral spirits in traditional Central African beliefs. This piece demonstrates the sophisticated artistry of tribal woodcarvers.",
    imageUrl: "/images/caseStudies/artifacts/artifact10.jpg",
    modelUrl: "/models/artifact8.glb",
    weight: "265.40 oz",
    height: "42.20 cm",
  },
  {
    id: "ceremonial-mask",
    title: "Ceremonial Mask",
    date: "Early 20th Century",
    location: "East Africa",
    currentLocation: "Nairobi, National Museum",
    description:
      "Elaborate ceremonial mask used in traditional coming-of-age rituals. The intricate patterns and colors hold deep cultural significance in the community's spiritual practices.",
    imageUrl: "/images/caseStudies/artifacts/artifact11.jpg",
    modelUrl: "/models/artifact9.glb",
    weight: "72.15 oz",
    height: "31.50 cm",
  },
  {
    id: "ceremonial-mask",
    title: "Ceremonial Mask",
    date: "Early 20th Century",
    location: "East Africa",
    currentLocation: "Nairobi, National Museum",
    description:
      "Elaborate ceremonial mask used in traditional coming-of-age rituals. The intricate patterns and colors hold deep cultural significance in the community's spiritual practices.",
    imageUrl: "/images/caseStudies/artifacts/artifact12.jpg",
    modelUrl: "/models/artifact9.glb",
    weight: "72.15 oz",
    height: "31.50 cm",
  },
  {
    id: "ceremonial-mask",
    title: "Ceremonial Mask",
    date: "Early 20th Century",
    location: "East Africa",
    currentLocation: "Nairobi, National Museum",
    description:
      "Elaborate ceremonial mask used in traditional coming-of-age rituals. The intricate patterns and colors hold deep cultural significance in the community's spiritual practices.",
    imageUrl: "/images/caseStudies/caseStudy artifact 3.jpg",
    modelUrl: "/models/artifact9.glb",
    weight: "72.15 oz",
    height: "31.50 cm",
  },
  {
    id: "artifact-1",
    title: "Artifact 1",
    date: "18th Century",
    location: "West Africa",
    currentLocation: "Museum Collection, Accra",
    description: "Traditional ceremonial artifact with intricate craftsmanship",
    imageUrl: "/images/caseStudies/artifacts/1.jpg",
    modelUrl: "/models/artifact.glb",
    weight: "95.50 oz",
    height: "28.75 cm",
  },
  {
    id: "artifact-1-1",
    title: "Artifact 1(1)",
    date: "19th Century",
    location: "East Africa",
    currentLocation: "National Heritage Museum, Nairobi",
    description: "Sacred vessel used in traditional ceremonies and rituals",
    imageUrl: "/images/caseStudies/artifacts/1(1).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "87.25 oz",
    height: "32.10 cm",
  },
  {
    id: "artifact-1-2",
    title: "Artifact 1(2)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(2).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-3",
    title: "Artifact 1(3)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(3).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-4",
    title: "Artifact 1(4)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(4).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-5",
    title: "Artifact 1(5)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(5).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-6",
    title: "Artifact 1(6)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(6).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-7",
    title: "Artifact 1(7)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(7).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-8",
    title: "Artifact 1(8)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(8).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-9",
    title: "Artifact 1(9)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(9).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-10",
    title: "Artifact 1(10)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(10).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-11",
    title: "Artifact 1(11)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(11).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-12",
    title: "Artifact 1(12)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(12).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-13",
    title: "Artifact 1(13)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(13).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-14",
    title: "Artifact 1(14)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(14).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-15",
    title: "Artifact 1(15)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(15).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-16",
    title: "Artifact 1(16)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(16).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-17",
    title: "Artifact 1(17)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(17).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-18",
    title: "Artifact 1(18)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(18).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-19",
    title: "Artifact 1(19)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(19).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-20",
    title: "Artifact 1(20)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(20).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-21",
    title: "Artifact 1(21)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(21).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-22",
    title: "Artifact 1(22)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(22).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-23",
    title: "Artifact 1(23)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(23).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-24",
    title: "Artifact 1(24)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(24).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-25",
    title: "Artifact 1(25)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(25).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-26",
    title: "Artifact 1(26)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(26).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-27",
    title: "Artifact 1(27)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(27).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-28",
    title: "Artifact 1(28)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(28).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-29",
    title: "Artifact 1(29)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(29).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-30",
    title: "Artifact 1(30)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(30).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-31",
    title: "Artifact 1(31)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(31).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-32",
    title: "Artifact 1(32)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(32).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-33",
    title: "Artifact 1(33)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(33).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-34",
    title: "Artifact 1(34)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(34).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-35",
    title: "Artifact 1(35)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(35).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-36",
    title: "Artifact 1(36)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(36).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-37",
    title: "Artifact 1(37)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(37).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-38",
    title: "Artifact 1(38)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(38).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-39",
    title: "Artifact 1(39)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(39).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-40",
    title: "Artifact 1(40)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(40).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-41",
    title: "Artifact 1(41)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(41).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-42",
    title: "Artifact 1(42)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(42).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-43",
    title: "Artifact 1(43)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(43).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-44",
    title: "Artifact 1(44)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(44).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-45",
    title: "Artifact 1(45)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(45).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-46",
    title: "Artifact 1(46)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(46).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-47",
    title: "Artifact 1(47)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(47).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-48",
    title: "Artifact 1(48)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(48).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-49",
    title: "Artifact 1(49)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(49).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-50",
    title: "Artifact 1(50)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(50).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-51",
    title: "Artifact 1(51)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(51).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-52",
    title: "Artifact 1(52)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(52).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-53",
    title: "Artifact 1(53)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(53).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-54",
    title: "Artifact 1(54)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(54).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-55",
    title: "Artifact 1(55)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(55).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-56",
    title: "Artifact 1(56)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(56).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-57",
    title: "Artifact 1(57)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(57).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
  {
    id: "artifact-1-58",
    title: "Artifact 1(58)",
    date: "Unknown",
    location: "Unknown",
    currentLocation: "Unknown",
    description: "Artifact from collection",
    imageUrl: "/images/caseStudies/artifacts/1(58).jpg",
    modelUrl: "/models/artifact.glb",
    weight: "Unknown",
    height: "Unknown",
  },
];

// Helper function to get an artifact by ID
export const getArtifactById = (id: string): Artifact | undefined => {
  return allArtifacts.find(artifact => artifact.id === id);
};
